use anyhow::Result;

fn shell_script() -> &'static str {
    r#"# ez shell integration — generated by `ez shell-init`
# Add to your .bashrc/.zshrc:  eval "$(ez shell-init)"

ez() {
    case "$1" in
        create|delete|switch|checkout|co|up|down|top|bottom)
            local _ez_path
            _ez_path=$(EZ_SHELL_INTEGRATION=1 command ez "$@")
            local _ez_exit=$?
            if [ $_ez_exit -eq 0 ] && [ -n "$_ez_path" ] && [ -d "$_ez_path" ]; then
                cd "$_ez_path" || true
            fi
            return $_ez_exit
            ;;
        merge|sync|fold)
            local _ez_path
            _ez_path=$(EZ_SHELL_INTEGRATION=1 command ez "$@")
            local _ez_exit=$?
            if [ -n "$_ez_path" ] && [ -d "$_ez_path" ]; then
                cd "$_ez_path" || true
            fi
            return $_ez_exit
            ;;
        worktree)
            if [ "$2" = "create" ] || [ "$2" = "delete" ]; then
                local _ez_path
                _ez_path=$(EZ_SHELL_INTEGRATION=1 command ez "$@")
                local _ez_exit=$?
                if [ $_ez_exit -eq 0 ] && [ -n "$_ez_path" ] && [ -d "$_ez_path" ]; then
                    cd "$_ez_path" || true
                fi
                return $_ez_exit
            fi
            ;;
    esac
    command ez "$@"
}
"#
}

pub fn run() -> Result<()> {
    print!("{}", shell_script());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::process::{Command, Stdio};

    #[test]
    fn shell_script_wraps_sync_and_worktree_navigation() {
        let script = shell_script();
        assert!(script.contains("create|delete|switch|checkout|co|up|down|top|bottom"));
        assert!(script.contains("merge|sync|fold)"));
        assert!(script.contains("worktree)"));
        assert!(script.contains("EZ_SHELL_INTEGRATION=1 command ez \"$@\""));
        assert!(script.contains("command ez \"$@\""));
    }

    #[test]
    fn shell_script_is_valid_bash() {
        let mut child = Command::new("bash")
            .arg("-n")
            .stdin(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("spawn bash -n");

        child
            .stdin
            .as_mut()
            .expect("bash stdin")
            .write_all(shell_script().as_bytes())
            .expect("write shell script to bash stdin");

        let output = child.wait_with_output().expect("wait for bash -n");
        assert!(
            output.status.success(),
            "shell script should parse as bash:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
