use anyhow::Result;

fn shell_script() -> &'static str {
    r#"# ez shell integration — generated by `ez shell-init`
# Add to your .bashrc/.zshrc:  eval "$(ez shell-init)"

ez() {{
    case "$1" in
        create|delete|switch|checkout|co|up|down|top|bottom)
            local _ez_path
            _ez_path=$(command ez "$@")
            local _ez_exit=$?
            if [ $_ez_exit -eq 0 ] && [ -n "$_ez_path" ] && [ -d "$_ez_path" ]; then
                cd "$_ez_path" || true
            fi
            return $_ez_exit
            ;;
        sync)
            local _ez_path
            _ez_path=$(command ez "$@")
            local _ez_exit=$?
            if [ -n "$_ez_path" ] && [ -d "$_ez_path" ]; then
                cd "$_ez_path" || true
            fi
            return $_ez_exit
            ;;
        worktree)
            if [ "$2" = "create" ] || [ "$2" = "delete" ]; then
                local _ez_path
                _ez_path=$(command ez "$@")
                local _ez_exit=$?
                if [ $_ez_exit -eq 0 ] && [ -n "$_ez_path" ] && [ -d "$_ez_path" ]; then
                    cd "$_ez_path" || true
                fi
                return $_ez_exit
            fi
            ;;
    esac
    command ez "$@"
}}
"#
}

pub fn run() -> Result<()> {
    print!("{}", shell_script());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shell_script_wraps_sync_and_worktree_navigation() {
        let script = shell_script();
        assert!(script.contains("create|delete|switch|checkout|co|up|down|top|bottom"));
        assert!(script.contains("sync)"));
        assert!(script.contains("worktree)"));
        assert!(script.contains("command ez \"$@\""));
    }
}
